require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CourseAreasController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # CourseArea. As you add validations to CourseArea, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CourseAreasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all course_areas as @course_areas" do
      course_area = CourseArea.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:course_areas)).to eq([course_area])
    end
  end

  describe "GET show" do
    it "assigns the requested course_area as @course_area" do
      course_area = CourseArea.create! valid_attributes
      get :show, {:id => course_area.to_param}, valid_session
      expect(assigns(:course_area)).to eq(course_area)
    end
  end

  describe "GET new" do
    it "assigns a new course_area as @course_area" do
      get :new, {}, valid_session
      expect(assigns(:course_area)).to be_a_new(CourseArea)
    end
  end

  describe "GET edit" do
    it "assigns the requested course_area as @course_area" do
      course_area = CourseArea.create! valid_attributes
      get :edit, {:id => course_area.to_param}, valid_session
      expect(assigns(:course_area)).to eq(course_area)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CourseArea" do
        expect {
          post :create, {:course_area => valid_attributes}, valid_session
        }.to change(CourseArea, :count).by(1)
      end

      it "assigns a newly created course_area as @course_area" do
        post :create, {:course_area => valid_attributes}, valid_session
        expect(assigns(:course_area)).to be_a(CourseArea)
        expect(assigns(:course_area)).to be_persisted
      end

      it "redirects to the created course_area" do
        post :create, {:course_area => valid_attributes}, valid_session
        expect(response).to redirect_to(CourseArea.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved course_area as @course_area" do
        post :create, {:course_area => invalid_attributes}, valid_session
        expect(assigns(:course_area)).to be_a_new(CourseArea)
      end

      it "re-renders the 'new' template" do
        post :create, {:course_area => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested course_area" do
        course_area = CourseArea.create! valid_attributes
        put :update, {:id => course_area.to_param, :course_area => new_attributes}, valid_session
        course_area.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested course_area as @course_area" do
        course_area = CourseArea.create! valid_attributes
        put :update, {:id => course_area.to_param, :course_area => valid_attributes}, valid_session
        expect(assigns(:course_area)).to eq(course_area)
      end

      it "redirects to the course_area" do
        course_area = CourseArea.create! valid_attributes
        put :update, {:id => course_area.to_param, :course_area => valid_attributes}, valid_session
        expect(response).to redirect_to(course_area)
      end
    end

    describe "with invalid params" do
      it "assigns the course_area as @course_area" do
        course_area = CourseArea.create! valid_attributes
        put :update, {:id => course_area.to_param, :course_area => invalid_attributes}, valid_session
        expect(assigns(:course_area)).to eq(course_area)
      end

      it "re-renders the 'edit' template" do
        course_area = CourseArea.create! valid_attributes
        put :update, {:id => course_area.to_param, :course_area => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested course_area" do
      course_area = CourseArea.create! valid_attributes
      expect {
        delete :destroy, {:id => course_area.to_param}, valid_session
      }.to change(CourseArea, :count).by(-1)
    end

    it "redirects to the course_areas list" do
      course_area = CourseArea.create! valid_attributes
      delete :destroy, {:id => course_area.to_param}, valid_session
      expect(response).to redirect_to(course_areas_url)
    end
  end

end
